/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Morning Night Dream - AppGateway
 * This is the AppGateway API documentation.
 * OpenAPI spec version: 0.0.1
 */
import useSwr from 'swr'
import type {
  SWRConfiguration,
  Key
} from 'swr'
import { customInstance } from '.././client';


  
  // eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * APIバージョン
 * @summary APIバージョン
 */
export const v1APIVersion = (
    
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<void>(
      {url: `/v1/version/api`, method: 'get'
    },
      options);
    }
  

export const getV1APIVersionKey = () => [`/v1/version/api`];

    
export type V1APIVersionQueryResult = NonNullable<Awaited<ReturnType<typeof v1APIVersion>>>
export type V1APIVersionQueryError = unknown

export const useV1APIVersion = <TError = unknown>(
  options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof v1APIVersion>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }

  ) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getV1APIVersionKey() : null);
  const swrFn = () => v1APIVersion(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Coreバージョン
 * @summary Coreバージョン
 */
export const v1CoreVersion = (
    
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<void>(
      {url: `/v1/version/core`, method: 'get'
    },
      options);
    }
  

export const getV1CoreVersionKey = () => [`/v1/version/core`];

    
export type V1CoreVersionQueryResult = NonNullable<Awaited<ReturnType<typeof v1CoreVersion>>>
export type V1CoreVersionQueryError = unknown

export const useV1CoreVersion = <TError = unknown>(
  options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof v1CoreVersion>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }

  ) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getV1CoreVersionKey() : null);
  const swrFn = () => v1CoreVersion(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

