/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Morning Night Guild - App API
 * This is the AppAPI API documentation.
 * OpenAPI spec version: 0.0.1
 */
import type { ArticleSchema } from './articleSchema';

export interface V1ArticleListResponseSchema {
  articles?: ArticleSchema[];
  /** 次回リクエスト時に指定するページトークン */
  nextPageToken?: string;
}
