/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Morning Night Guild - App API
 * This is the AppAPI API documentation.
 * OpenAPI spec version: 0.0.1
 */

export interface V1AuthVerifyUnauthorizedResponseSchema {
  /** リフレッシュコード
このコードを使用してトークンを新たに取得することができます。
リフレッシュできる見込みがない場合(セッショントークンがない状態でのリクエスト)ではリフレッシュ用コードは払い出しません。 */
  code: string;
}
