/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Morning Night Guild - App API
 * This is the AppAPI API documentation.
 * OpenAPI spec version: 0.0.1
 */

export interface V1AuthSignUpRequestSchema {
  /** メールアドレス */
  email: string;
  /** パスワード */
  password: string;
}
