/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Morning Night Dream - AppGateway
 * This is the AppGateway API documentation.
 * OpenAPI spec version: 0.0.1
 */
import type { Article } from './article';

export interface V1ListArticleResponse {
  articles?: Article[];
  /** 次回リクエスト時に指定するページトークン */
  nextPageToken?: string;
}
